spring:
  data:
    mongodb:
      uri: ${MONGO_URL_COMPLETA:mongodb://localhost:27017/desafio}

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    root: INFO