version: "2.1"

networks:
  bridge-apivotacao:
    driver: bridge

services:

  mongodb_apivotacao:
    image: docker.io/bitnami/mongodb:6.0
    ports:
      - 27017:27017
    container_name: mongodb_apivotacao
    volumes:
      - 'mongodb_data:/bitnami/mongodb'
    networks:
      - bridge-apivotacao

  apivotacao:
    build: ./sessoesdevoto
    ports:
      - 8080:8080
    container_name: apivotacao
    depends_on:
      - mongodb_apivotacao
    environment:
      - MONGO_URL_COMPLETA=mongodb://mongodb_apivotacao:27017/apivotacao
      - PERFIL_DE_CONFIG=prod
    networks:
      - bridge-apivotacao

volumes:
  mongodb_data:
    driver: local